name: cicd-pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m pytest tests/

      - name: Start FastAPI server and check health
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5  # Wait for the server to start
          curl http://localhost:8000/